In [3]:
import pandas as pd
import numpy as np

In [4]:
pd.__version__

'2.3.2'

In [8]:
df = pd.read_csv("car_fuel_efficiency.csv")

In [9]:
df.shape

(9704, 11)

In [10]:
df.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [11]:
df['fuel_type'].nunique()

2

In [12]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [13]:
df.groupby('origin')['fuel_efficiency_mpg'].max().round(2)

origin
Asia      23.76
Europe    25.97
USA       24.97
Name: fuel_efficiency_mpg, dtype: float64

In [14]:
df['horsepower'].median().round(2)

np.float64(149.0)

In [15]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [16]:
df1 = df

df1['horsepower'] = df1['horsepower'].fillna(152.0)

In [17]:
df1['horsepower'].median().round(2)

np.float64(152.0)

In [41]:
df2 = df.loc[df['origin'] == 'Asia', ['vehicle_weight','model_year']]

In [42]:
s = df2.iloc[[0,1,2,3,4,5,6]]

In [43]:
X = s.values

In [44]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [49]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [50]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [47]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [51]:
r = inv_XTX.dot(X.T).dot(y)

In [52]:
r.sum()

np.float64(0.5187709081074016)