# Numpy

In [1]:
import numpy as np

In [3]:
np

<module 'numpy' from 'd:\\Programs\\Python\\Lib\\site-packages\\numpy\\__init__.py'>

### Creating array

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1,5,1,2,3])
a

array([1, 5, 1, 2, 3])

In [12]:
a[3] = 9
a

array([1, 5, 1, 9, 3])

In [14]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(0,4,11)

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. ])

### Multi-dimentional Array

In [22]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
n=np.array([
    [1,2,3],
    [4,5,6]
])

n

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
n[1][0]

np.int64(4)

In [31]:
n[1][0] = 40
n[1]

array([40,  5,  6])

In [33]:
n[1] = [7,8,9]
n

array([[1, 2, 3],
       [7, 8, 9]])

In [35]:
n[:,1]

array([2, 8])

### Random Array

In [40]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [41]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [42]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [48]:
np.random.seed(2)
np.random.randint(low=0,high=100,size = (5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

### Element-wise Operations

In [50]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])